package classes;

import classes.Entry;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;

public class EntryPanel extends javax.swing.JPanel {

    private Entry entry;
    EntryPanel me;
    
    public EntryPanel(Entry entry) {
        this.entry = entry;
        initComponents();
    }

    public JButton getDeleteEntryButton() {
        return deleteEntryButton;
    }
    
    public ImageIcon scaleImage(ImageIcon icon, int w, int h) {
        int nw = icon.getIconWidth();
        int nh = icon.getIconHeight();

        if(icon.getIconWidth() > w) {
          nw = w;
          nh = (nw * icon.getIconHeight()) / icon.getIconWidth();
        }

        if(nh > h) {
          nh = h;
          nw = (icon.getIconWidth() * nh) / icon.getIconHeight();
        }

        return new ImageIcon(icon.getImage().getScaledInstance(nw, nh, Image.SCALE_DEFAULT));
    }
    
    
    public void loadData(){
        entryTitleLabel.setText(entry.getTitle());
        entryTextArea.setText(entry.getText());
        entryLocationLabel.setText(entry.getLocation());
        entryTimeLabel.setText(entry.getTime().toString());
        
        if(entry.getPic() != null) {
            int width = 240;
            int height = 150;
            entryImageLabel.setPreferredSize(new Dimension(width, height));
            entryImageLabel.setIcon(scaleImage(entry.getPic(), width, height));
            this.revalidate();
            this.repaint();
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        entryTextArea = new javax.swing.JTextArea();
        entryTitleLabel = new javax.swing.JLabel();
        entryTimeLabel = new javax.swing.JLabel();
        entryImageLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        editEntryButton = new javax.swing.JButton();
        deleteEntryButton = new javax.swing.JButton();
        entryLocationLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(44, 61, 81));
        setMaximumSize(new java.awt.Dimension(646, 455));
        setMinimumSize(new java.awt.Dimension(646, 290));
        setPreferredSize(new java.awt.Dimension(646, 290));

        entryTextArea.setEditable(false);
        entryTextArea.setBackground(new java.awt.Color(232, 224, 213));
        entryTextArea.setColumns(20);
        entryTextArea.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        entryTextArea.setForeground(new java.awt.Color(44, 61, 81));
        entryTextArea.setLineWrap(true);
        entryTextArea.setRows(5);
        entryTextArea.setText("amdbba da;lmd/lnk\nd\nd\na\nd\na");
        entryTextArea.setWrapStyleWord(true);
        entryTextArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        entryTextArea.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jScrollPane1.setViewportView(entryTextArea);

        entryTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        entryTitleLabel.setForeground(new java.awt.Color(181, 196, 201));
        entryTitleLabel.setText("Title here");

        entryTimeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        entryTimeLabel.setForeground(new java.awt.Color(181, 196, 201));
        entryTimeLabel.setText("Time here");

        jSeparator1.setForeground(new java.awt.Color(232, 224, 213));

        editEntryButton.setBackground(new java.awt.Color(181, 196, 201));
        editEntryButton.setForeground(new java.awt.Color(44, 61, 81));
        editEntryButton.setText("...");
        editEntryButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        editEntryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEntryButtonActionPerformed(evt);
            }
        });

        deleteEntryButton.setBackground(new java.awt.Color(181, 196, 201));
        deleteEntryButton.setForeground(new java.awt.Color(44, 61, 81));
        deleteEntryButton.setText("X");
        deleteEntryButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        deleteEntryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEntryButtonActionPerformed(evt);
            }
        });

        entryLocationLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        entryLocationLabel.setForeground(new java.awt.Color(181, 196, 201));
        entryLocationLabel.setText("Location here");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(entryTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(editEntryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteEntryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(entryTimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                                .addComponent(entryLocationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(entryImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(entryTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(editEntryButton, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addComponent(deleteEntryButton, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(entryTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(entryLocationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(entryImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteEntryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEntryButtonActionPerformed
        me = this;
        me.getParent().remove(me);
        me.getParent().revalidate();
        me.getParent().repaint();
    }//GEN-LAST:event_deleteEntryButtonActionPerformed

    private void editEntryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEntryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editEntryButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteEntryButton;
    private javax.swing.JButton editEntryButton;
    private javax.swing.JLabel entryImageLabel;
    private javax.swing.JLabel entryLocationLabel;
    private javax.swing.JTextArea entryTextArea;
    private javax.swing.JLabel entryTimeLabel;
    private javax.swing.JLabel entryTitleLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
